DROP TABLE IF EXISTS passwords CASCADE;

CREATE TABLE passwords (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) DELETE ON CASCADE,
  category_id INTEGER REFERENCES categories(id) DELETE ON CASCADE,
  password VARCHAR(128),
  website VARCHAR(255),
  username VARCHAR(255)
);
